version: "3.8"

services:
  linux-container:
    build: .
    container_name: linux_env
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - internal

  flask-app:
    build: ../python
    container_name: flask_app
    ports:
      - "5000:80"
    networks:
      - internal
    depends_on:
      - linux-container

networks:
  internal:
    driver: bridge
